// <auto-generated />
using System;
using FuelManagementSoftware.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FuelManagementSoftware.Migrations
{
    [DbContext(typeof(FuelManagementSoftwareDbContext))]
    [Migration("20260219092812_InitialSqlite")]
    partial class InitialSqlite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.23");

            modelBuilder.Entity("FuelManagementSoftware.Models.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Changes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now', 'utc')");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("creator_id");

                    b.Property<int?>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("OrganisationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("organisation_id");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK__AuditLog__3214EC0766CE7448");

                    b.HasIndex(new[] { "Action" }, "IX_AuditLogs_Action");

                    b.HasIndex(new[] { "CreatedAt" }, "IX_AuditLogs_CreatedAt");

                    b.HasIndex(new[] { "EntityId" }, "IX_AuditLogs_EntityId");

                    b.HasIndex(new[] { "EntityType" }, "IX_AuditLogs_EntityType");

                    b.HasIndex(new[] { "UserId" }, "IX_AuditLogs_UserId");

                    b.HasIndex(new[] { "CreatorId" }, "IX_AuditLogs_creator_id");

                    b.HasIndex(new[] { "OrganisationId" }, "IX_AuditLogs_organisation_id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("FuelManagementSoftware.Models.BlockchainTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("BlockNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BlockchainHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("BlockchainNetwork")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ConfirmationCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now', 'utc')");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("creator_id");

                    b.Property<int>("FuelTransactionId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("GasPrice")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<decimal?>("GasUsed")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<int>("OrganisationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("organisation_id");

                    b.Property<string>("PreviousHash")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("SmartContractAddress")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Pending");

                    b.Property<int?>("TransactionIndex")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id")
                        .HasName("PK__Blockcha__3214EC0703A4D565");

                    b.HasIndex(new[] { "BlockchainHash" }, "IX_BlockchainTransactions_BlockchainHash");

                    b.HasIndex(new[] { "CreatedAt" }, "IX_BlockchainTransactions_CreatedAt");

                    b.HasIndex(new[] { "FuelTransactionId" }, "IX_BlockchainTransactions_FuelTransactionId");

                    b.HasIndex(new[] { "Status" }, "IX_BlockchainTransactions_Status");

                    b.HasIndex(new[] { "CreatorId" }, "IX_BlockchainTransactions_creator_id");

                    b.HasIndex(new[] { "OrganisationId" }, "IX_BlockchainTransactions_organisation_id");

                    b.HasIndex(new[] { "BlockchainHash" }, "UQ__Blockcha__D5ABDAFF2DA25C72")
                        .IsUnique();

                    b.ToTable("BlockchainTransactions");
                });

            modelBuilder.Entity("FuelManagementSoftware.Models.CardTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("BalanceAfter")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("BalanceBefore")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("creator_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("USD");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("OrganisationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("organisation_id");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("PetroCardId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TransactionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now', 'utc')");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK__CardTran__3214EC07015D32F2");

                    b.HasIndex(new[] { "PetroCardId" }, "IX_CardTransactions_PetroCardId");

                    b.HasIndex(new[] { "TransactionDate" }, "IX_CardTransactions_TransactionDate");

                    b.HasIndex(new[] { "TransactionType" }, "IX_CardTransactions_TransactionType");

                    b.HasIndex(new[] { "CreatorId" }, "IX_CardTransactions_creator_id");

                    b.HasIndex(new[] { "OrganisationId" }, "IX_CardTransactions_organisation_id");

                    b.ToTable("CardTransactions");
                });

            modelBuilder.Entity("FuelManagementSoftware.Models.FuelPump", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now', 'utc')");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("creator_id");

                    b.Property<int>("FuelStationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FuelTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsOperational")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastMaintenanceDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrganisationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("organisation_id");

                    b.Property<string>("PumpNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK__FuelPump__3214EC0766109EC3");

                    b.HasIndex("FuelTypeId");

                    b.HasIndex(new[] { "FuelStationId" }, "IX_FuelPumps_FuelStationId");

                    b.HasIndex(new[] { "CreatorId" }, "IX_FuelPumps_creator_id");

                    b.HasIndex(new[] { "OrganisationId" }, "IX_FuelPumps_organisation_id");

                    b.ToTable("FuelPumps");
                });

            modelBuilder.Entity("FuelManagementSoftware.Models.FuelStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now', 'utc')");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("creator_id");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsOpen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsTankerOffloading")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(10, 8)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(11, 8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("OrganisationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("organisation_id");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK__FuelStat__3214EC07AA22693D");

                    b.HasIndex(new[] { "IsActive" }, "IX_FuelStations_IsActive");

                    b.HasIndex(new[] { "IsOpen" }, "IX_FuelStations_IsOpen");

                    b.HasIndex(new[] { "Latitude", "Longitude" }, "IX_FuelStations_Location");

                    b.HasIndex(new[] { "CreatorId" }, "IX_FuelStations_creator_id");

                    b.HasIndex(new[] { "OrganisationId" }, "IX_FuelStations_organisation_id");

                    b.ToTable("FuelStations");
                });

            modelBuilder.Entity("FuelManagementSoftware.Models.FuelStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Capacity")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now', 'utc')");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("creator_id");

                    b.Property<decimal>("CurrentQuantity")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("FuelStationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FuelTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLowStock")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now', 'utc')");

                    b.Property<decimal?>("LowStockThreshold")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("OrganisationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("organisation_id");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Litre");

                    b.HasKey("Id")
                        .HasName("PK__FuelStoc__3214EC07B8E88608");

                    b.HasIndex(new[] { "FuelStationId" }, "IX_FuelStock_FuelStationId");

                    b.HasIndex(new[] { "FuelTypeId" }, "IX_FuelStock_FuelTypeId");

                    b.HasIndex(new[] { "LastUpdated" }, "IX_FuelStock_LastUpdated");

                    b.HasIndex(new[] { "CreatorId" }, "IX_FuelStock_creator_id");

                    b.HasIndex(new[] { "OrganisationId" }, "IX_FuelStock_organisation_id");

                    b.HasIndex(new[] { "FuelStationId", "FuelTypeId" }, "UQ_FuelStock_Station_FuelType")
                        .IsUnique();

                    b.ToTable("FuelStock");
                });

            modelBuilder.Entity("FuelManagementSoftware.Models.FuelTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("creator_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("USD");

                    b.Property<int>("FuelPumpId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FuelStationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FuelTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("OrganisationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("organisation_id");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PetroCardId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("TransactionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now', 'utc')");

                    b.Property<string>("TransactionNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Completed");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK__FuelTran__3214EC0768AD478D");

                    b.HasIndex("FuelTypeId");

                    b.HasIndex(new[] { "FuelPumpId" }, "IX_FuelTransactions_FuelPumpId");

                    b.HasIndex(new[] { "FuelStationId" }, "IX_FuelTransactions_FuelStationId");

                    b.HasIndex(new[] { "PetroCardId" }, "IX_FuelTransactions_PetroCardId");

                    b.HasIndex(new[] { "TransactionDate" }, "IX_FuelTransactions_TransactionDate");

                    b.HasIndex(new[] { "TransactionNumber" }, "IX_FuelTransactions_TransactionNumber");

                    b.HasIndex(new[] { "TransactionStatus" }, "IX_FuelTransactions_TransactionStatus");

                    b.HasIndex(new[] { "UserId" }, "IX_FuelTransactions_UserId");

                    b.HasIndex(new[] { "CreatorId" }, "IX_FuelTransactions_creator_id");

                    b.HasIndex(new[] { "OrganisationId" }, "IX_FuelTransactions_organisation_id");

                    b.HasIndex(new[] { "TransactionNumber" }, "UQ__FuelTran__E733A2BF3216A763")
                        .IsUnique();

                    b.ToTable("FuelTransactions");
                });

            modelBuilder.Entity("FuelManagementSoftware.Models.FuelType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now', 'utc')");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("creator_id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("OrganisationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("organisation_id");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Litre");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK__FuelType__3214EC0785D74B7C");

                    b.HasIndex(new[] { "CreatorId" }, "IX_FuelTypes_creator_id");

                    b.HasIndex(new[] { "OrganisationId" }, "IX_FuelTypes_organisation_id");

                    b.ToTable("FuelTypes");
                });

            modelBuilder.Entity("FuelManagementSoftware.Models.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now', 'utc')");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("creator_id");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK__Organiza__3214EC0701075EE5");

                    b.HasIndex(new[] { "Code" }, "IX_Organizations_Code");

                    b.HasIndex(new[] { "CreatorId" }, "IX_Organizations_creator_id");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("FuelManagementSoftware.Models.PetroCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now', 'utc')");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("creator_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("USD");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrganisationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("organisation_id");

                    b.Property<string>("PinHash")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Rfidtag")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("RFIDTag");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK__PetroCar__3214EC0781ADAEA4");

                    b.HasIndex(new[] { "CardNumber" }, "IX_PetroCards_CardNumber");

                    b.HasIndex(new[] { "IsActive" }, "IX_PetroCards_IsActive");

                    b.HasIndex(new[] { "Rfidtag" }, "IX_PetroCards_RFIDTag");

                    b.HasIndex(new[] { "UserId" }, "IX_PetroCards_UserId");

                    b.HasIndex(new[] { "CreatorId" }, "IX_PetroCards_creator_id");

                    b.HasIndex(new[] { "OrganisationId" }, "IX_PetroCards_organisation_id");

                    b.HasIndex(new[] { "Rfidtag" }, "UQ__PetroCar__411E34E6E9D8F135")
                        .IsUnique();

                    b.HasIndex(new[] { "CardNumber" }, "UQ__PetroCar__A4E9FFE9DD1223D2")
                        .IsUnique();

                    b.ToTable("PetroCards");
                });

            modelBuilder.Entity("FuelManagementSoftware.Models.QueueInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActivePumps")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("creator_id");

                    b.Property<int>("EstimatedQueueLength")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EstimatedWaitTimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FuelStationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrganisationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("organisation_id");

                    b.Property<DateTime>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now', 'utc')");

                    b.HasKey("Id")
                        .HasName("PK__QueueInf__3214EC07222CE06D");

                    b.HasIndex(new[] { "FuelStationId" }, "IX_QueueInformation_FuelStationId");

                    b.HasIndex(new[] { "RecordedAt" }, "IX_QueueInformation_RecordedAt");

                    b.HasIndex(new[] { "CreatorId" }, "IX_QueueInformation_creator_id");

                    b.HasIndex(new[] { "OrganisationId" }, "IX_QueueInformation_organisation_id");

                    b.ToTable("QueueInformation");
                });

            modelBuilder.Entity("FuelManagementSoftware.Models.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NormalizedName" }, "RoleNameIndex")
                        .IsUnique()
                        .HasFilter("([NormalizedName] IS NOT NULL)");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("FuelManagementSoftware.Models.RoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "RoleId" }, "IX_RoleClaims_RoleId");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("FuelManagementSoftware.Models.StationStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("creator_id");

                    b.Property<DateTime?>("ExpectedReopenTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("FuelStationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("OrganisationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("organisation_id");

                    b.Property<string>("PreviousStatus")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StatusChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now', 'utc')");

                    b.Property<string>("StatusType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK__StationS__3214EC07C6F93A9A");

                    b.HasIndex(new[] { "FuelStationId" }, "IX_StationStatusHistory_FuelStationId");

                    b.HasIndex(new[] { "StatusChangedAt" }, "IX_StationStatusHistory_StatusChangedAt");

                    b.HasIndex(new[] { "StatusType" }, "IX_StationStatusHistory_StatusType");

                    b.HasIndex(new[] { "CreatorId" }, "IX_StationStatusHistory_creator_id");

                    b.HasIndex(new[] { "OrganisationId" }, "IX_StationStatusHistory_organisation_id");

                    b.ToTable("StationStatusHistory");
                });

            modelBuilder.Entity("FuelManagementSoftware.Models.StockMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("creator_id");

                    b.Property<string>("DeliveryNoteNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DriverName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("FuelStationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FuelTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("MovementDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now', 'utc')");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("OrganisationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("organisation_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StockAfter")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("StockBefore")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TankerRegistration")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Litre");

                    b.HasKey("Id")
                        .HasName("PK__StockMov__3214EC077571867C");

                    b.HasIndex(new[] { "FuelStationId" }, "IX_StockMovements_FuelStationId");

                    b.HasIndex(new[] { "FuelTypeId" }, "IX_StockMovements_FuelTypeId");

                    b.HasIndex(new[] { "MovementDate" }, "IX_StockMovements_MovementDate");

                    b.HasIndex(new[] { "MovementType" }, "IX_StockMovements_MovementType");

                    b.HasIndex(new[] { "CreatorId" }, "IX_StockMovements_creator_id");

                    b.HasIndex(new[] { "OrganisationId" }, "IX_StockMovements_organisation_id");

                    b.ToTable("StockMovements");
                });

            modelBuilder.Entity("FuelManagementSoftware.Models.SystemConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfigurationKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigurationValue")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now', 'utc')");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("creator_id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<int>("OrganisationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("organisation_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK__SystemCo__3214EC07E66E31AD");

                    b.HasIndex(new[] { "ConfigurationKey" }, "IX_SystemConfigurations_ConfigurationKey");

                    b.HasIndex(new[] { "CreatorId" }, "IX_SystemConfigurations_creator_id");

                    b.HasIndex(new[] { "OrganisationId" }, "IX_SystemConfigurations_organisation_id");

                    b.HasIndex(new[] { "OrganisationId", "ConfigurationKey" }, "UQ_SystemConfigurations_Org_Key")
                        .IsUnique();

                    b.ToTable("SystemConfigurations");
                });

            modelBuilder.Entity("FuelManagementSoftware.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NormalizedEmail" }, "EmailIndex");

                    b.HasIndex(new[] { "NormalizedUserName" }, "UserNameIndex")
                        .IsUnique()
                        .HasFilter("([NormalizedUserName] IS NOT NULL)");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FuelManagementSoftware.Models.UserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "IX_UserClaims_UserId");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("FuelManagementSoftware.Models.UserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex(new[] { "UserId" }, "IX_UserLogins_UserId");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("FuelManagementSoftware.Models.UserToken", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("RoleId", "UserId");

                    b.ToTable("RoleUser");
                });

            modelBuilder.Entity("UserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex(new[] { "RoleId" }, "IX_UserRoles_RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("FuelManagementSoftware.Models.AuditLog", b =>
                {
                    b.HasOne("FuelManagementSoftware.Models.User", "Creator")
                        .WithMany("AuditLogCreators")
                        .HasForeignKey("CreatorId")
                        .IsRequired()
                        .HasConstraintName("FK_AuditLogs_Creator");

                    b.HasOne("FuelManagementSoftware.Models.Organization", "Organisation")
                        .WithMany("AuditLogs")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AuditLogs_Organizations");

                    b.HasOne("FuelManagementSoftware.Models.User", "User")
                        .WithMany("AuditLogUsers")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_AuditLogs_Users");

                    b.Navigation("Creator");

                    b.Navigation("Organisation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FuelManagementSoftware.Models.BlockchainTransaction", b =>
                {
                    b.HasOne("FuelManagementSoftware.Models.User", "Creator")
                        .WithMany("BlockchainTransactions")
                        .HasForeignKey("CreatorId")
                        .IsRequired()
                        .HasConstraintName("FK_BlockchainTransactions_Users");

                    b.HasOne("FuelManagementSoftware.Models.FuelTransaction", "FuelTransaction")
                        .WithMany("BlockchainTransactions")
                        .HasForeignKey("FuelTransactionId")
                        .IsRequired()
                        .HasConstraintName("FK_BlockchainTransactions_FuelTransactions");

                    b.HasOne("FuelManagementSoftware.Models.Organization", "Organisation")
                        .WithMany("BlockchainTransactions")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BlockchainTransactions_Organizations");

                    b.Navigation("Creator");

                    b.Navigation("FuelTransaction");

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("FuelManagementSoftware.Models.CardTransaction", b =>
                {
                    b.HasOne("FuelManagementSoftware.Models.User", "Creator")
                        .WithMany("CardTransactions")
                        .HasForeignKey("CreatorId")
                        .IsRequired()
                        .HasConstraintName("FK_CardTransactions_Users");

                    b.HasOne("FuelManagementSoftware.Models.Organization", "Organisation")
                        .WithMany("CardTransactions")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CardTransactions_Organizations");

                    b.HasOne("FuelManagementSoftware.Models.PetroCard", "PetroCard")
                        .WithMany("CardTransactions")
                        .HasForeignKey("PetroCardId")
                        .IsRequired()
                        .HasConstraintName("FK_CardTransactions_PetroCards");

                    b.Navigation("Creator");

                    b.Navigation("Organisation");

                    b.Navigation("PetroCard");
                });

            modelBuilder.Entity("FuelManagementSoftware.Models.FuelPump", b =>
                {
                    b.HasOne("FuelManagementSoftware.Models.User", "Creator")
                        .WithMany("FuelPumps")
                        .HasForeignKey("CreatorId")
                        .IsRequired()
                        .HasConstraintName("FK_FuelPumps_Users");

                    b.HasOne("FuelManagementSoftware.Models.FuelStation", "FuelStation")
                        .WithMany("FuelPumps")
                        .HasForeignKey("FuelStationId")
                        .IsRequired()
                        .HasConstraintName("FK_FuelPumps_FuelStations");

                    b.HasOne("FuelManagementSoftware.Models.FuelType", "FuelType")
                        .WithMany("FuelPumps")
                        .HasForeignKey("FuelTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_FuelPumps_FuelTypes");

                    b.HasOne("FuelManagementSoftware.Models.Organization", "Organisation")
                        .WithMany("FuelPumps")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FuelPumps_Organizations");

                    b.Navigation("Creator");

                    b.Navigation("FuelStation");

                    b.Navigation("FuelType");

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("FuelManagementSoftware.Models.FuelStation", b =>
                {
                    b.HasOne("FuelManagementSoftware.Models.User", "Creator")
                        .WithMany("FuelStations")
                        .HasForeignKey("CreatorId")
                        .IsRequired()
                        .HasConstraintName("FK_FuelStations_Users");

                    b.HasOne("FuelManagementSoftware.Models.Organization", "Organisation")
                        .WithMany("FuelStations")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FuelStations_Organizations");

                    b.Navigation("Creator");

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("FuelManagementSoftware.Models.FuelStock", b =>
                {
                    b.HasOne("FuelManagementSoftware.Models.User", "Creator")
                        .WithMany("FuelStocks")
                        .HasForeignKey("CreatorId")
                        .IsRequired()
                        .HasConstraintName("FK_FuelStock_Users");

                    b.HasOne("FuelManagementSoftware.Models.FuelStation", "FuelStation")
                        .WithMany("FuelStocks")
                        .HasForeignKey("FuelStationId")
                        .IsRequired()
                        .HasConstraintName("FK_FuelStock_FuelStations");

                    b.HasOne("FuelManagementSoftware.Models.FuelType", "FuelType")
                        .WithMany("FuelStocks")
                        .HasForeignKey("FuelTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_FuelStock_FuelTypes");

                    b.HasOne("FuelManagementSoftware.Models.Organization", "Organisation")
                        .WithMany("FuelStocks")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FuelStock_Organizations");

                    b.Navigation("Creator");

                    b.Navigation("FuelStation");

                    b.Navigation("FuelType");

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("FuelManagementSoftware.Models.FuelTransaction", b =>
                {
                    b.HasOne("FuelManagementSoftware.Models.User", "Creator")
                        .WithMany("FuelTransactionCreators")
                        .HasForeignKey("CreatorId")
                        .IsRequired()
                        .HasConstraintName("FK_FuelTransactions_Creator");

                    b.HasOne("FuelManagementSoftware.Models.FuelPump", "FuelPump")
                        .WithMany("FuelTransactions")
                        .HasForeignKey("FuelPumpId")
                        .IsRequired()
                        .HasConstraintName("FK_FuelTransactions_FuelPumps");

                    b.HasOne("FuelManagementSoftware.Models.FuelStation", "FuelStation")
                        .WithMany("FuelTransactions")
                        .HasForeignKey("FuelStationId")
                        .IsRequired()
                        .HasConstraintName("FK_FuelTransactions_FuelStations");

                    b.HasOne("FuelManagementSoftware.Models.FuelType", "FuelType")
                        .WithMany("FuelTransactions")
                        .HasForeignKey("FuelTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_FuelTransactions_FuelTypes");

                    b.HasOne("FuelManagementSoftware.Models.Organization", "Organisation")
                        .WithMany("FuelTransactions")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FuelTransactions_Organizations");

                    b.HasOne("FuelManagementSoftware.Models.PetroCard", "PetroCard")
                        .WithMany("FuelTransactions")
                        .HasForeignKey("PetroCardId")
                        .HasConstraintName("FK_FuelTransactions_PetroCards");

                    b.HasOne("FuelManagementSoftware.Models.User", "User")
                        .WithMany("FuelTransactionUsers")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_FuelTransactions_Users");

                    b.Navigation("Creator");

                    b.Navigation("FuelPump");

                    b.Navigation("FuelStation");

                    b.Navigation("FuelType");

                    b.Navigation("Organisation");

                    b.Navigation("PetroCard");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FuelManagementSoftware.Models.FuelType", b =>
                {
                    b.HasOne("FuelManagementSoftware.Models.User", "Creator")
                        .WithMany("FuelTypes")
                        .HasForeignKey("CreatorId")
                        .IsRequired()
                        .HasConstraintName("FK_FuelTypes_Users");

                    b.HasOne("FuelManagementSoftware.Models.Organization", "Organisation")
                        .WithMany("FuelTypes")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FuelTypes_Organizations");

                    b.Navigation("Creator");

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("FuelManagementSoftware.Models.Organization", b =>
                {
                    b.HasOne("FuelManagementSoftware.Models.User", "Creator")
                        .WithMany("Organizations")
                        .HasForeignKey("CreatorId")
                        .IsRequired()
                        .HasConstraintName("FK_Organizations_Users");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("FuelManagementSoftware.Models.PetroCard", b =>
                {
                    b.HasOne("FuelManagementSoftware.Models.User", "Creator")
                        .WithMany("PetroCardCreators")
                        .HasForeignKey("CreatorId")
                        .IsRequired()
                        .HasConstraintName("FK_PetroCards_Creator");

                    b.HasOne("FuelManagementSoftware.Models.Organization", "Organisation")
                        .WithMany("PetroCards")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PetroCards_Organizations");

                    b.HasOne("FuelManagementSoftware.Models.User", "User")
                        .WithMany("PetroCardUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PetroCards_Users");

                    b.Navigation("Creator");

                    b.Navigation("Organisation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FuelManagementSoftware.Models.QueueInformation", b =>
                {
                    b.HasOne("FuelManagementSoftware.Models.User", "Creator")
                        .WithMany("QueueInformations")
                        .HasForeignKey("CreatorId")
                        .IsRequired()
                        .HasConstraintName("FK_QueueInformation_Users");

                    b.HasOne("FuelManagementSoftware.Models.FuelStation", "FuelStation")
                        .WithMany("QueueInformations")
                        .HasForeignKey("FuelStationId")
                        .IsRequired()
                        .HasConstraintName("FK_QueueInformation_FuelStations");

                    b.HasOne("FuelManagementSoftware.Models.Organization", "Organisation")
                        .WithMany("QueueInformations")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_QueueInformation_Organizations");

                    b.Navigation("Creator");

                    b.Navigation("FuelStation");

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("FuelManagementSoftware.Models.RoleClaim", b =>
                {
                    b.HasOne("FuelManagementSoftware.Models.Role", "Role")
                        .WithMany("RoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("FuelManagementSoftware.Models.StationStatusHistory", b =>
                {
                    b.HasOne("FuelManagementSoftware.Models.User", "Creator")
                        .WithMany("StationStatusHistories")
                        .HasForeignKey("CreatorId")
                        .IsRequired()
                        .HasConstraintName("FK_StationStatusHistory_Users");

                    b.HasOne("FuelManagementSoftware.Models.FuelStation", "FuelStation")
                        .WithMany("StationStatusHistories")
                        .HasForeignKey("FuelStationId")
                        .IsRequired()
                        .HasConstraintName("FK_StationStatusHistory_FuelStations");

                    b.HasOne("FuelManagementSoftware.Models.Organization", "Organisation")
                        .WithMany("StationStatusHistories")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_StationStatusHistory_Organizations");

                    b.Navigation("Creator");

                    b.Navigation("FuelStation");

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("FuelManagementSoftware.Models.StockMovement", b =>
                {
                    b.HasOne("FuelManagementSoftware.Models.User", "Creator")
                        .WithMany("StockMovements")
                        .HasForeignKey("CreatorId")
                        .IsRequired()
                        .HasConstraintName("FK_StockMovements_Users");

                    b.HasOne("FuelManagementSoftware.Models.FuelStation", "FuelStation")
                        .WithMany("StockMovements")
                        .HasForeignKey("FuelStationId")
                        .IsRequired()
                        .HasConstraintName("FK_StockMovements_FuelStations");

                    b.HasOne("FuelManagementSoftware.Models.FuelType", "FuelType")
                        .WithMany("StockMovements")
                        .HasForeignKey("FuelTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_StockMovements_FuelTypes");

                    b.HasOne("FuelManagementSoftware.Models.Organization", "Organisation")
                        .WithMany("StockMovements")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_StockMovements_Organizations");

                    b.Navigation("Creator");

                    b.Navigation("FuelStation");

                    b.Navigation("FuelType");

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("FuelManagementSoftware.Models.SystemConfiguration", b =>
                {
                    b.HasOne("FuelManagementSoftware.Models.User", "Creator")
                        .WithMany("SystemConfigurations")
                        .HasForeignKey("CreatorId")
                        .IsRequired()
                        .HasConstraintName("FK_SystemConfigurations_Users");

                    b.HasOne("FuelManagementSoftware.Models.Organization", "Organisation")
                        .WithMany("SystemConfigurations")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SystemConfigurations_Organizations");

                    b.Navigation("Creator");

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("FuelManagementSoftware.Models.UserClaim", b =>
                {
                    b.HasOne("FuelManagementSoftware.Models.User", "User")
                        .WithMany("UserClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FuelManagementSoftware.Models.UserLogin", b =>
                {
                    b.HasOne("FuelManagementSoftware.Models.User", "User")
                        .WithMany("UserLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FuelManagementSoftware.Models.UserToken", b =>
                {
                    b.HasOne("FuelManagementSoftware.Models.User", "User")
                        .WithMany("UserTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserRole", b =>
                {
                    b.HasOne("FuelManagementSoftware.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FuelManagementSoftware.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FuelManagementSoftware.Models.FuelPump", b =>
                {
                    b.Navigation("FuelTransactions");
                });

            modelBuilder.Entity("FuelManagementSoftware.Models.FuelStation", b =>
                {
                    b.Navigation("FuelPumps");

                    b.Navigation("FuelStocks");

                    b.Navigation("FuelTransactions");

                    b.Navigation("QueueInformations");

                    b.Navigation("StationStatusHistories");

                    b.Navigation("StockMovements");
                });

            modelBuilder.Entity("FuelManagementSoftware.Models.FuelTransaction", b =>
                {
                    b.Navigation("BlockchainTransactions");
                });

            modelBuilder.Entity("FuelManagementSoftware.Models.FuelType", b =>
                {
                    b.Navigation("FuelPumps");

                    b.Navigation("FuelStocks");

                    b.Navigation("FuelTransactions");

                    b.Navigation("StockMovements");
                });

            modelBuilder.Entity("FuelManagementSoftware.Models.Organization", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("BlockchainTransactions");

                    b.Navigation("CardTransactions");

                    b.Navigation("FuelPumps");

                    b.Navigation("FuelStations");

                    b.Navigation("FuelStocks");

                    b.Navigation("FuelTransactions");

                    b.Navigation("FuelTypes");

                    b.Navigation("PetroCards");

                    b.Navigation("QueueInformations");

                    b.Navigation("StationStatusHistories");

                    b.Navigation("StockMovements");

                    b.Navigation("SystemConfigurations");
                });

            modelBuilder.Entity("FuelManagementSoftware.Models.PetroCard", b =>
                {
                    b.Navigation("CardTransactions");

                    b.Navigation("FuelTransactions");
                });

            modelBuilder.Entity("FuelManagementSoftware.Models.Role", b =>
                {
                    b.Navigation("RoleClaims");
                });

            modelBuilder.Entity("FuelManagementSoftware.Models.User", b =>
                {
                    b.Navigation("AuditLogCreators");

                    b.Navigation("AuditLogUsers");

                    b.Navigation("BlockchainTransactions");

                    b.Navigation("CardTransactions");

                    b.Navigation("FuelPumps");

                    b.Navigation("FuelStations");

                    b.Navigation("FuelStocks");

                    b.Navigation("FuelTransactionCreators");

                    b.Navigation("FuelTransactionUsers");

                    b.Navigation("FuelTypes");

                    b.Navigation("Organizations");

                    b.Navigation("PetroCardCreators");

                    b.Navigation("PetroCardUsers");

                    b.Navigation("QueueInformations");

                    b.Navigation("StationStatusHistories");

                    b.Navigation("StockMovements");

                    b.Navigation("SystemConfigurations");

                    b.Navigation("UserClaims");

                    b.Navigation("UserLogins");

                    b.Navigation("UserTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
